### ISSUE TITLE
feat: implement CodeInput component

### ISSUE THREAD

**Issue by TahimiLeonBravo** [nexxtway/react-rainbow#1488]
#### Tasks
- [x] Define API
- [x] Implement component
- [ ] Add unit and integration test

### Use Cases
- [x] As a user, I want to type the code received.
- [x] As a user, I want to be able to paste a code copied.

#### Expected Behavior
- [x] It should follow the accessibility specs of an inputable component.
- [x] Each separated input element should be focusable.
- [x] It should follow the keyboard navigation specs.
- [x] It should copy only the numbers if the value copied have letters
- [x] Only the first values of the copied value should be copied to the input if it is too long
- [x] It should open when focusing the numeric keyboard on the phone
- [x] It should move focus on the next element when typing an any element
- [x] It should move the focus back when deleting some element
- [x] It should only get the focus on the element where you have to type
- [x] It should not move the over the elements when press `tab` key, only one element gets the focus (the element where you have to type)

##### API
https://docs.google.com/document/d/1PAFwTznCcUdz3_Vp9NJ5o0EFm3N4qcRY2GWQ1IXGl7Q/edit?usp=sharing

##### Design
Design Guidelines
https://zpl.io/V0BrvBR

Interactive Examples
https://zpl.io/adJKdeL

- - - - - - - - - - - - - - - - - - - - - - - - - 

**SPECS**

### CodeInput

- [x] should have value length as 6 when length is 6
- [x] should have label rendered if label is sent as param
- [x] should not have label rendered when label is emtpy
- [x] should have bottomHelpText rendered if is sent as param
- [x] should not have bottomHelpText rendered when bottomHelpText is empty
- [x] should have error rendered if is sent as param
- [x] should not have error rendered if is not sent as param
- [x] should keep isActive as true on active input whenever any other input is clicked
- [x] should set isActive as true over the second input when first input is filled
- [x] should keep isActive as true on the last input when all inputs are filled an last input changes
- [x] should call onChange with the number value when input value changes and is number
- [x] should not call onChange when input value changes and is not a number (UPDATED)
- [x] should call getNumbersFromClipboard with the copied and pasted value
- [x] should call onChange with numbers only when we copy and paste a mixed text and numbers string (NEW)
- [x] should call getNormalizedValue with the right values when value changes
- [x] should call useValueState with the right value and length
- [x] should call useFocusedIndexState with the right value and length
- [x] should call usePreviousIndex with the right focusedIndex value

### InputItems
- [x] should have 4 InputItem elements rendered when value array has a length of 4
- [x] should have isActive only on the focusedIndex input
- [x] should have tabIndex passed only to the focusedIndex input
- [x] should have the initial values properly assigned to each input
- [x] should have ref passed only to the focusedIndex input

### InputItem
- [x] should call onChange event with the right value and index when input changes
- [x] should call onChange event with empty value when DELETE_KEY is pressed, current input value is empty and current index is greater than 0
- [x] should not call onChange when DELETE_KEY is pressed, current input value is empty and current index is 0
- [x] should call onClick event with the right value when input is clicked
- [x] should call onFocus event with the right value and index when input is focused
- [x] should call onBlur event with the right value when input leaves focus
- [x] should call onKeyDown event with the right value when key is pressed
- [x] should call onPaste event with the right value when string is pasted inside input

#### getNormalizedValue
- [x] should return empty if inputValue is not number
- [x] should return the right normalized value by joining current array value with new value
- [x] should return the right normalized value when removing value from index 1

#### getNumbersFromClipboard
- [x] should return empty if value is empty
- [x] should return numbers only if value is string mixed with numbers

#### getValueArray
- [x] should return an array with 2 empty positions when value is number and maxLength is 2
- [x] should return an array with 3 positions filled with numbers when a mixed text and numbers are passed as value and maxLength is 3
- [x] should return an array with the last position empty when value is a string with two numbers and maxLength is 3

#### isNumeric
- [x] should return true if value is number
- [x] should return false if value is not number
- [x] should return false if value is empty

#### setFocus
- [x] should call ref focus() and select() methods when ref is valid
- [x] should not call ref focus() nor select() methods when ref is invalid

#### useFocusedIndexState
- [x] should return index 0 (first position) when value is empty and length is 4
- [x] should return index 2 when value is has two numbers and length is 4
- [x] should return index 3 (last position) when value has 4 numbers and length is 4

#### usePreviousIndex
- [x] should return previousIndex undefined on hook initialization
- [x] should return previous focused index after focusedIndex is updated; it is controlled by useRef internally inside usePreviousIndex hook (UPDATE)

#### useValueState
- [x] should return array of four values when value is '1234' and length is 4

#### readme.md - base example - 1
- [x] should have focus on the first input on load
- [x] should change focus to the second input when the first input its filled with a number
- [x] should remove value from first input when first input is selected, has a value and "Backspace" key is pressed (NEW)
- [x] should return focus to the first input and clear his value when the first input has a value, the second input is empty, is focused and "Backspace" key is pressed
- [x] should keep focus on the first input when input is empty and "Backspace" key is pressed
- [x] should keep focus on the last input when the last input value is filled with a number
- [x] should keep focus in the current input when we type a letter
- [x] should keep value empty in the current input when we type a letter (NEW)
- [x] should keep current input focus when unfocused inputs are clicked
- [x] should keep focus on the second input when any input is clicked and the first input has a number already
- [x] should leave focus on all inputs when "Tab" key is pressed
- [x] should return focus to the active input when "Tab" key is pressed and then any of the non active inputs is clicked
- [x] should have all inputs filled when we type 4 numbers in a row and codeInput has a length of 4

#### readme.md - disabled example - 9
- [x] should keep inputs unfocused when codeInput is disabled and inputs are clicked

**Comment by TahimiLeonBravo** [comment]
#1524 and #1538
