### ISSUE TITLE
fix: Picklist is closing when the search input is clicked

### ISSUE THREAD

**Issue by HellWolf93** [nexxtway/react-rainbow#2416]
-   [x] I have searched the [issues](https://github.com/nexxtway/react-rainbow/issues) of this repository and believe that this is not a duplicate.

## Describe the bug

When the user click on the search input of the Picklist, the dropdown is closed.

## TODO:
- [ ] Fix the bug
- [ ] Un-skip the test that check this behaviour.

**Comment by LeandroTorresSicilia** [comment]
solved by #2516
